// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcwy4Vot-y4q9iEOy4XiO-FnSlMf6v-cI',
    appId: '1:969751104277:web:b73897421f6cc45381b71c',
    messagingSenderId: '969751104277',
    projectId: 'formapp-d4e9e',
    authDomain: 'formapp-d4e9e.firebaseapp.com',
    storageBucket: 'formapp-d4e9e.firebasestorage.app',
    measurementId: 'G-14D8C5Y9FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3CYfQswYolL-ItfcR4_0L75kFmE4KVE8',
    appId: '1:969751104277:android:c14ee26fe691eb7781b71c',
    messagingSenderId: '969751104277',
    projectId: 'formapp-d4e9e',
    storageBucket: 'formapp-d4e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA179wZBgpdUQ3oPpkbUYJGkWjNsr-Jtpg',
    appId: '1:969751104277:ios:99ffadc07816d5ce81b71c',
    messagingSenderId: '969751104277',
    projectId: 'formapp-d4e9e',
    storageBucket: 'formapp-d4e9e.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );
}
